package electrolysis;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.*;
import java.util.StringTokenizer;
import javax.swing.*;
/**
 *
 * @author ASPIRE P2QG
 */
public class Menu1stFrame extends javax.swing.JFrame {
    public static String userEmail;
    /**
     * Creates new form StartingFrame
     */
    public Menu1stFrame() {
        initComponents();
        setLocationRelativeTo(null);
        //setName();
    }
    //to set the name label
    public static void setName() {
        File accounts = new File("accounts.txt");

        try{
            if(!accounts.exists()) {
                accounts.createNewFile();
            }

            FileReader accountsFR = new FileReader(accounts);
            BufferedReader reader = new BufferedReader(accountsFR);
            String line;
            while((line=reader.readLine())!=null) {
                StringTokenizer strTokenizer = new StringTokenizer(line, ",");
                String email = "" + strTokenizer.nextElement();
                if(userEmail.equals(email)) {
                    String name = "" + strTokenizer.nextElement();
                    yourScienceHelperLabel.setText("Hi, " + name + "!");
                }
            }
            //CLOSING
            accountsFR.close();
            reader.close();

        } catch(IOException e){
            //JOptionPane.showMessageDialog(this, "IOException");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBackgroundPanel = new javax.swing.JPanel();
        chooseHelperPanel = new javax.swing.JPanel();
        chemButton = new javax.swing.JButton();
        bioButton = new javax.swing.JButton();
        physButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        accountPanel = new javax.swing.JPanel();
        deleteAccountButton = new javax.swing.JButton();
        updateAccountButton = new javax.swing.JButton();
        yourScienceHelperLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sciencebook");
        setBackground(new java.awt.Color(47, 87, 85));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        mainBackgroundPanel.setBackground(new java.awt.Color(38, 38, 38));
        mainBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 10));
        mainBackgroundPanel.setPreferredSize(new java.awt.Dimension(766, 450));

        chooseHelperPanel.setBackground(new java.awt.Color(38, 38, 38));
        chooseHelperPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 4), " CHOOSE HELPER ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 18), new java.awt.Color(0, 255, 255))); // NOI18N

        chemButton.setBackground(new java.awt.Color(0, 255, 255));
        chemButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        chemButton.setForeground(new java.awt.Color(38, 38, 38));
        chemButton.setText("METAL PRODUCTION CALCULATOR");
        chemButton.setBorder(null);
        chemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemButtonActionPerformed(evt);
            }
        });

        bioButton.setBackground(new java.awt.Color(0, 255, 255));
        bioButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        bioButton.setForeground(new java.awt.Color(38, 38, 38));
        bioButton.setText("RNA TO PROTEIN TRANSLATOR");
        bioButton.setBorder(null);
        bioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioButtonActionPerformed(evt);
            }
        });

        physButton.setBackground(new java.awt.Color(0, 255, 255));
        physButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        physButton.setForeground(new java.awt.Color(38, 38, 38));
        physButton.setText("VECTOR SUMMATION CALCULATOR");
        physButton.setBorder(null);
        physButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseHelperPanelLayout = new javax.swing.GroupLayout(chooseHelperPanel);
        chooseHelperPanel.setLayout(chooseHelperPanelLayout);
        chooseHelperPanelLayout.setHorizontalGroup(
            chooseHelperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseHelperPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(chooseHelperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(physButton, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addComponent(chemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        chooseHelperPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bioButton, chemButton});

        chooseHelperPanelLayout.setVerticalGroup(
            chooseHelperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseHelperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(physButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        exitButton.setBackground(new java.awt.Color(0, 204, 204));
        exitButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(38, 38, 38));
        exitButton.setText("Log Out");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        accountPanel.setBackground(new java.awt.Color(38, 38, 38));
        accountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 4), " YOUR ACCOUNT ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 18), new java.awt.Color(0, 255, 255))); // NOI18N

        deleteAccountButton.setBackground(new java.awt.Color(0, 255, 255));
        deleteAccountButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        deleteAccountButton.setForeground(new java.awt.Color(38, 38, 38));
        deleteAccountButton.setText("DELETE ACCOUNT");
        deleteAccountButton.setBorder(null);
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        updateAccountButton.setBackground(new java.awt.Color(0, 255, 255));
        updateAccountButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 24)); // NOI18N
        updateAccountButton.setForeground(new java.awt.Color(38, 38, 38));
        updateAccountButton.setText("UPDATE ACCOUNT");
        updateAccountButton.setBorder(null);
        updateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteAccountButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateAccountButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        yourScienceHelperLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        yourScienceHelperLabel.setForeground(new java.awt.Color(0, 255, 255));
        yourScienceHelperLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourScienceHelperLabel.setText("Hi, Jim Yvene S. Cadion!");

        javax.swing.GroupLayout mainBackgroundPanelLayout = new javax.swing.GroupLayout(mainBackgroundPanel);
        mainBackgroundPanel.setLayout(mainBackgroundPanelLayout);
        mainBackgroundPanelLayout.setHorizontalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(yourScienceHelperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBackgroundPanelLayout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBackgroundPanelLayout.createSequentialGroup()
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBackgroundPanelLayout.createSequentialGroup()
                                .addGroup(mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chooseHelperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))))))
        );
        mainBackgroundPanelLayout.setVerticalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(yourScienceHelperLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseHelperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        new IndexFrame().setVisible(true);
        Menu1stFrame.setName();
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void chemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemButtonActionPerformed
        new MetalProdCalcCalculator().setVisible(true);
        MetalProdCalcCalculator.userEmail = this.userEmail;
        MetalProdCalcHistory.userEmail = this.userEmail;
        MetalProdCalcSummary.userEmail = this.userEmail;
        this.setVisible(false);
    }//GEN-LAST:event_chemButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        int deleteCounter = 0;
        //ACCOUNT DATA IN METAL PRODUCTION
        File accountFile = new File("accounts.txt");
        if(JOptionPane.showConfirmDialog(this,"Are you sure to delete this account?","Warning!",JOptionPane.YES_NO_OPTION)==0){
            try{
                //EXCEPTION HANDLING
                if(!accountFile.exists()) {
                    accountFile.createNewFile();
                }

                //DELETING THE HISTORY
                FileReader fileR = new FileReader(accountFile);
                BufferedReader reader = new BufferedReader(fileR);
                StringBuffer buffer = new StringBuffer();
                String line;

                while ((line=reader.readLine()) != null){
                    if(!line.contains(userEmail)) {
                        buffer.append(line);
                        buffer.append("\r");
                    }
                }

                String fileContents = buffer.toString();
                fileR.close();
                reader.close();
                FileWriter fileW = new FileWriter(accountFile);
                fileW.write(fileContents);
                fileW.flush();
                fileW.close();

                deleteCounter++;
                //CLOSING
                fileR.close();
                reader.close();
            } catch(IOException e){
                JOptionPane.showMessageDialog(null, "IOException");
            }

            //ACCOUNT DATA IN METAL PRODUCTION
            File metalProdFile = new File("metalProduction.txt");
            try{
                //EXCEPTION HANDLING
                if(!metalProdFile.exists()) {
                    metalProdFile.createNewFile();
                }

                //DELETING THE HISTORY
                FileReader fileR = new FileReader(metalProdFile);
                BufferedReader reader = new BufferedReader(fileR);
                StringBuffer buffer = new StringBuffer();
                String line;

                while ((line=reader.readLine()) != null){
                    if(!line.contains(userEmail)) {
                        buffer.append(line);
                        buffer.append("\r");
                    }
                }

                String fileContents = buffer.toString();
                fileR.close();
                reader.close();
                FileWriter fileW = new FileWriter(metalProdFile);
                fileW.write(fileContents);
                fileW.flush();
                fileW.close();
                deleteCounter++;

                //CLOSING
                fileR.close();
                reader.close();


            } catch(IOException e){
                JOptionPane.showMessageDialog(null, "IOException");
            }
            
            //ACCOUNT DATA IN METAL PRODUCTION
            File vectorFile = new File("vectorCalculator.txt");
            try{
                //EXCEPTION HANDLING
                if(!vectorFile.exists()) {
                    vectorFile.createNewFile();
                }

                //DELETING THE HISTORY
                FileReader fileR = new FileReader(vectorFile);
                BufferedReader reader = new BufferedReader(fileR);
                StringBuffer buffer = new StringBuffer();
                String line;

                while ((line=reader.readLine()) != null){
                    if(!line.contains(userEmail)) {
                        buffer.append(line);
                        buffer.append("\r");
                    }
                }

                String fileContents = buffer.toString();
                fileR.close();
                reader.close();
                FileWriter fileW = new FileWriter(vectorFile);
                fileW.write(fileContents);
                fileW.flush();
                fileW.close();
                deleteCounter++;

                //CLOSING
                fileR.close();
                reader.close();


            } catch(IOException e){
                JOptionPane.showMessageDialog(null, "IOException");
            }
            
            //ACCOUNT DATA IN METAL PRODUCTION
            File bioFile = new File("Biology Sciencebook.txt");
            try{
                //EXCEPTION HANDLING
                if(!bioFile.exists()) {
                    bioFile.createNewFile();
                }

                //DELETING THE HISTORY
                FileReader fileR = new FileReader(bioFile);
                BufferedReader reader = new BufferedReader(fileR);
                StringBuffer buffer = new StringBuffer();
                String line;

                while ((line=reader.readLine()) != null){
                    if(!line.contains(userEmail)) {
                        buffer.append(line);
                        buffer.append("\r");
                    }
                }

                String fileContents = buffer.toString();
                fileR.close();
                reader.close();
                FileWriter fileW = new FileWriter(bioFile);
                fileW.write(fileContents);
                fileW.flush();
                fileW.close();
                deleteCounter++;

                //CLOSING
                fileR.close();
                reader.close();


            } catch(IOException e){
                JOptionPane.showMessageDialog(null, "IOException");
            }
            
            //if(deleteCounter==4) {//////////////////////////////////////////////////////////////////
            JOptionPane.showMessageDialog(this, "Account successfully deleted.");
            new IndexFrame().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    private void updateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccountButtonActionPerformed
        new UpdateAccountFrame().setVisible(true);
        File accounts = new File("accounts.txt");

        try{
            if(!accounts.exists()) {
                accounts.createNewFile();
            }

            FileReader accountsFR = new FileReader(accounts);
            BufferedReader reader = new BufferedReader(accountsFR);
            String line;
            while((line=reader.readLine())!=null) {
                StringTokenizer strTokenizer = new StringTokenizer(line, ",");
                String email = "" + strTokenizer.nextElement();
                if(userEmail.equals(email)) {
                    String name = "" + strTokenizer.nextElement();
                    String age = "" + strTokenizer.nextElement();
                    String password = "" + strTokenizer.nextElement();
                    UpdateAccountFrame.nameTF.setText(name);
                    UpdateAccountFrame.ageTF.setText(age);
                    UpdateAccountFrame.passwordPF1.setText(password);
                    UpdateAccountFrame.emailTF1.setText(email);
                }
            }
            //CLOSING
            accountsFR.close();
            reader.close();

        } catch(IOException e){
            //JOptionPane.showMessageDialog(this, "IOException");
        }
        this.setVisible(false);
    }//GEN-LAST:event_updateAccountButtonActionPerformed

    private void bioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioButtonActionPerformed
        BioFun.userEmail = this.userEmail;
        BioGenerator.userEmail = this.userEmail;
        BioHistory.userEmail = this.userEmail;
        new BioGenerator().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bioButtonActionPerformed

    private void physButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physButtonActionPerformed
        VectorSum.userEmail = this.userEmail;
        VectorSumHistory.userEmail = this.userEmail;
        new VectorSum().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_physButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JButton bioButton;
    private javax.swing.JButton chemButton;
    private javax.swing.JPanel chooseHelperPanel;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel mainBackgroundPanel;
    private javax.swing.JButton physButton;
    private javax.swing.JButton updateAccountButton;
    public static javax.swing.JLabel yourScienceHelperLabel;
    // End of variables declaration//GEN-END:variables

}


