package electrolysis;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.*;
import java.util.StringTokenizer;
import javax.swing.*;
/**
 *
 * @author ASPIRE P2QG
 */
public class MetalProdCalcSummary extends javax.swing.JFrame {
    public static String userEmail;
    static String[] metalsArr = {"Li", "K", "Ba", "Ca", "Na", "Mg", "Al", "Zn", "Cr", "Fe", "Co", "Ni", "Sn", "Pb", "Cu", "Hg", "Ag", "Au", "Pt", "Sr"};
    
    /**
     * Creates new form StartingFrame
     */
    public MetalProdCalcSummary() {
        initComponents();
        setLocationRelativeTo(null);
        showSummary();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBackgroundPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        calculatorButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        productionButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sciencebook");
        setBackground(new java.awt.Color(47, 87, 85));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        mainBackgroundPanel.setBackground(new java.awt.Color(38, 38, 38));
        mainBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 10));
        mainBackgroundPanel.setPreferredSize(new java.awt.Dimension(766, 450));

        menuPanel.setBackground(new java.awt.Color(0, 51, 51));
        menuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 130), 4), " SCIENCEBOOK: METAL PRODUCTION CALCULATOR ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 18), new java.awt.Color(0, 255, 255))); // NOI18N
        menuPanel.setForeground(new java.awt.Color(0, 51, 51));

        calculatorButton.setBackground(new java.awt.Color(0, 255, 255));
        calculatorButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        calculatorButton.setForeground(new java.awt.Color(0, 51, 51));
        calculatorButton.setText("CALCULATOR");
        calculatorButton.setBorder(null);
        calculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonActionPerformed(evt);
            }
        });

        historyButton.setBackground(new java.awt.Color(0, 255, 255));
        historyButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        historyButton.setForeground(new java.awt.Color(0, 51, 51));
        historyButton.setText("HISTORY");
        historyButton.setBorder(null);
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        productionButton.setBackground(new java.awt.Color(0, 204, 204));
        productionButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        productionButton.setForeground(new java.awt.Color(0, 51, 51));
        productionButton.setText("SUMMARY");
        productionButton.setBorder(null);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(productionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatorButton)
                    .addComponent(historyButton)
                    .addComponent(productionButton))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        exitButton.setBackground(new java.awt.Color(0, 204, 204));
        exitButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(38, 38, 38));
        exitButton.setText("Go Back to Helpers Menu");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        summaryTA.setEditable(false);
        summaryTA.setBackground(new java.awt.Color(51, 51, 51));
        summaryTA.setColumns(20);
        summaryTA.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        summaryTA.setForeground(new java.awt.Color(255, 255, 255));
        summaryTA.setRows(5);
        summaryTA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 4), " SUMMARY ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 18), new java.awt.Color(0, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(summaryTA);

        javax.swing.GroupLayout mainBackgroundPanelLayout = new javax.swing.GroupLayout(mainBackgroundPanel);
        mainBackgroundPanel.setLayout(mainBackgroundPanelLayout);
        mainBackgroundPanelLayout.setHorizontalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBackgroundPanelLayout.createSequentialGroup()
                .addGap(36, 342, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainBackgroundPanelLayout.setVerticalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void showSummary() {
        File metalProdFile = new File("metalProduction.txt");
        String line;
        summaryTA.setText("");
        try{
            //EXCEPTION HANDLING
            if(!metalProdFile.exists()) {
                metalProdFile.createNewFile();
            }
            
            //IMPORTANT DECLARATIONS
            double[] metalsTotMass = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
            double totMassProd = 0;
            double totTime = 0;
            
            //EXTRACTING IMPORTANT INFO FROM THE FILE
            FileReader fileR = new FileReader(metalProdFile);
            BufferedReader reader = new BufferedReader(fileR);
            while((line=reader.readLine())!=null) {
                if(line.contains(userEmail)) {
                    StringTokenizer strTokenizer = new StringTokenizer(line, "'");
                    String email = "" + strTokenizer.nextElement();
                    String metal = "" + strTokenizer.nextElement();
                    double current = Double.parseDouble("" + strTokenizer.nextElement());
                    double time = Double.parseDouble("" + strTokenizer.nextElement());
                    double metalProduced = Double.parseDouble("" + strTokenizer.nextElement());
                    String date = "" + strTokenizer.nextElement();
                    
                    int index = 0;
                    for(int x = 0; x < 20 ; x++) {
                        if(metal.equals(metalsArr[x])) {
                            index = x;
                        }
                    }
                    metalsTotMass[index] = metalsTotMass[index] + metalProduced;
                    totMassProd = totMassProd + metalProduced;
                    totTime = totTime + time;
                }
            }
            
            //OUTPUT SUMMARY
            summaryTA.append(String.format("   Total Mass of Metals Produced: %,.2fg%n", totMassProd));
            summaryTA.append(String.format("   Total Production Time: %,.2fhrs%n%n", totTime));
            summaryTA.append(String.format("   Individual Metal Production:%n", totTime));
            for(int y = 0; y < 20; y++) {
                if(metalsTotMass[y]!=0) {
                    summaryTA.append(String.format("   %s(s) :", metalsArr[y]) + "\t" + String.format("%,.2fg%n", metalsTotMass[y]));
                }
            }
            
            //CLOSING
            fileR.close();
            reader.close();
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "IOException");
        }
    }
    
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        new Menu1stFrame().setVisible(true);
        Menu1stFrame.setName();
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void calculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorButtonActionPerformed
        new MetalProdCalcCalculator().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_calculatorButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        new MetalProdCalcHistory().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_historyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculatorButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainBackgroundPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton productionButton;
    public static javax.swing.JTextArea summaryTA;
    // End of variables declaration//GEN-END:variables

}

