package electrolysis;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import electrolysis.*;
import java.io.*;
import java.util.StringTokenizer;
import javax.swing.*;
/**
 *
 * @author ASPIRE P2QG
 */
public class MetalProdCalcCalculator extends javax.swing.JFrame {
    public static String userEmail;
    static String[] metalsArr = {"Li", "K", "Ba", "Ca", "Na", "Mg", "Al", "Zn", "Cr", "Fe", "Co", "Ni", "Sn", "Pb", "Cu", "Hg", "Ag", "Au", "Pt", "Sr"};
    static double[] molarMass = {6.941, 39.098, 137.327, 40.078, 22.990, 24.305, 26.982, 65.409, 51.996, 55.845, 58.933, 58.693, 118.710, 207.2, 63.546, 200.592, 107.868, 196.967, 195.084, 87.62};
    private static int[] electrons = {1, 1, 2, 2, 1, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2};
    private double metalProduced = 0;
    
    /**
     * Creates new form StartingFrame
     */
    public MetalProdCalcCalculator() {
        initComponents();
        setLocationRelativeTo(null);
        //CLEARING THE FIELDS
            metalTF.setText("");
            currentTF.setText("");
            timeTF.setText("");
            
            metalProducedPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBackgroundPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        calculatorButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        productionButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        calculationPanel = new javax.swing.JPanel();
        calculateButton = new javax.swing.JButton();
        metallLabel = new javax.swing.JLabel();
        metalTF = new javax.swing.JTextField();
        currentLabel = new javax.swing.JLabel();
        currentTF = new javax.swing.JTextField();
        timeLabel = new javax.swing.JLabel();
        timeTF = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        dayTF = new javax.swing.JTextField();
        yearTF = new javax.swing.JTextField();
        monthTF = new javax.swing.JTextField();
        metalProducedPanel = new javax.swing.JPanel();
        metalProducedTF = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sciencebook");
        setBackground(new java.awt.Color(47, 87, 85));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        mainBackgroundPanel.setBackground(new java.awt.Color(38, 38, 38));
        mainBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 10));
        mainBackgroundPanel.setPreferredSize(new java.awt.Dimension(766, 450));

        menuPanel.setBackground(new java.awt.Color(0, 51, 51));
        menuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 130), 4), " SCIENCEBOOK: METAL PRODUCTION CALCULATOR ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 18), new java.awt.Color(0, 255, 255))); // NOI18N
        menuPanel.setForeground(new java.awt.Color(0, 51, 51));

        calculatorButton.setBackground(new java.awt.Color(0, 204, 204));
        calculatorButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        calculatorButton.setForeground(new java.awt.Color(0, 51, 51));
        calculatorButton.setText("CALCULATOR");
        calculatorButton.setBorder(null);

        historyButton.setBackground(new java.awt.Color(0, 255, 255));
        historyButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        historyButton.setForeground(new java.awt.Color(0, 51, 51));
        historyButton.setText("HISTORY");
        historyButton.setBorder(null);
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        productionButton.setBackground(new java.awt.Color(0, 255, 255));
        productionButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        productionButton.setForeground(new java.awt.Color(0, 51, 51));
        productionButton.setText("SUMMARY");
        productionButton.setBorder(null);
        productionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(productionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatorButton)
                    .addComponent(historyButton)
                    .addComponent(productionButton))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        exitButton.setBackground(new java.awt.Color(0, 204, 204));
        exitButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(38, 38, 38));
        exitButton.setText("Go Back to Helpers Menu");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        calculationPanel.setBackground(new java.awt.Color(38, 38, 38));
        calculationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 4), " CALCULATION ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 18), new java.awt.Color(0, 255, 255))); // NOI18N

        calculateButton.setBackground(new java.awt.Color(0, 255, 255));
        calculateButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 18)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(38, 38, 38));
        calculateButton.setText("CALCULATE");
        calculateButton.setBorder(null);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        metallLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        metallLabel.setForeground(new java.awt.Color(0, 255, 255));
        metallLabel.setText("Metal:");

        metalTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        metalTF.setForeground(new java.awt.Color(38, 38, 38));
        metalTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        metalTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 1));
        metalTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metalTFMouseClicked(evt);
            }
        });

        currentLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        currentLabel.setForeground(new java.awt.Color(0, 255, 255));
        currentLabel.setText("Current (A):");

        currentTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        currentTF.setForeground(new java.awt.Color(38, 38, 38));
        currentTF.setText("10000000");
        currentTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 1));
        currentTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentTFMouseClicked(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 255, 255));
        timeLabel.setText("Time (hrs):");

        timeTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        timeTF.setForeground(new java.awt.Color(38, 38, 38));
        timeTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        timeTF.setText("1");
        timeTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 1));
        timeTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeTFMouseClicked(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(0, 255, 255));
        dateLabel.setText("Date:");

        dayTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        dayTF.setForeground(new java.awt.Color(38, 38, 38));
        dayTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dayTF.setText("dd");
        dayTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 1));
        dayTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dayTFMouseClicked(evt);
            }
        });

        yearTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        yearTF.setForeground(new java.awt.Color(38, 38, 38));
        yearTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearTF.setText("yy");
        yearTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 1));
        yearTF.setPreferredSize(new java.awt.Dimension(35, 21));
        yearTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearTFMouseClicked(evt);
            }
        });

        monthTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        monthTF.setForeground(new java.awt.Color(38, 38, 38));
        monthTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthTF.setText("mm");
        monthTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 1));
        monthTF.setPreferredSize(new java.awt.Dimension(35, 21));
        monthTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthTFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout calculationPanelLayout = new javax.swing.GroupLayout(calculationPanel);
        calculationPanel.setLayout(calculationPanelLayout);
        calculationPanelLayout.setHorizontalGroup(
            calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculationPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLabel)
                    .addComponent(metallLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculationPanelLayout.createSequentialGroup()
                        .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calculationPanelLayout.createSequentialGroup()
                                .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(metalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currentTF)
                            .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(calculationPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        calculationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dayTF, monthTF, yearTF});

        calculationPanelLayout.setVerticalGroup(
            calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculationPanelLayout.createSequentialGroup()
                        .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(dayTF)
                            .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monthTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metallLabel)
                            .addComponent(metalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(calculationPanelLayout.createSequentialGroup()
                        .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentLabel)
                            .addComponent(currentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        calculationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {currentTF, dayTF, metalTF, monthTF, timeTF, yearTF});

        metalProducedPanel.setBackground(new java.awt.Color(38, 38, 38));
        metalProducedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3), " METAL PRODUCED ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 16), new java.awt.Color(0, 255, 255))); // NOI18N

        metalProducedTF.setBackground(new java.awt.Color(38, 38, 38));
        metalProducedTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        metalProducedTF.setForeground(new java.awt.Color(255, 255, 255));
        metalProducedTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        metalProducedTF.setText("500,000.00g of Ag(s)");
        metalProducedTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 1));

        saveButton.setBackground(new java.awt.Color(0, 255, 255));
        saveButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(38, 38, 38));
        saveButton.setText("SAVE");
        saveButton.setBorder(null);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout metalProducedPanelLayout = new javax.swing.GroupLayout(metalProducedPanel);
        metalProducedPanel.setLayout(metalProducedPanelLayout);
        metalProducedPanelLayout.setHorizontalGroup(
            metalProducedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metalProducedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metalProducedTF, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(metalProducedPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        metalProducedPanelLayout.setVerticalGroup(
            metalProducedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metalProducedPanelLayout.createSequentialGroup()
                .addComponent(metalProducedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainBackgroundPanelLayout = new javax.swing.GroupLayout(mainBackgroundPanel);
        mainBackgroundPanel.setLayout(mainBackgroundPanelLayout);
        mainBackgroundPanelLayout.setHorizontalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(metalProducedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calculationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        mainBackgroundPanelLayout.setVerticalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(calculationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(metalProducedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        new Menu1stFrame().setVisible(true);
        Menu1stFrame.setName();
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        try{
            //EXCEPTION HANDLING
            if(metalTF.getText().equals("") ||  currentTF.getText().equals("") || timeTF.getText().equals("")) {
                throw new BlankException();
            }
            
            if(monthTF.getText().equals("") || dayTF.getText().equals("") || yearTF.getText().equals("") || monthTF.getText().length()!=2 || dayTF.getText().length()!=2 || yearTF.getText().length()!=2) {
                throw new WrongDateException();
            }
            
            if(Integer.parseInt(dayTF.getText()) > 31 || Integer.parseInt(monthTF.getText()) > 12 || Integer.parseInt(monthTF.getText()) == 0 || Integer.parseInt(dayTF.getText()) == 0) {
                throw new DateNotExistException();
            }
            if((Integer.parseInt(monthTF.getText()) == 4 || Integer.parseInt(monthTF.getText()) == 6 || Integer.parseInt(monthTF.getText()) == 9 || Integer.parseInt(monthTF.getText()) == 11) && Integer.parseInt(dayTF.getText()) >= 31){
                throw new DateNotExistException();
            }
            else if (Integer.parseInt(monthTF.getText()) == 2){
                if (Integer.parseInt(yearTF.getText())%4 != 0 && Integer.parseInt(dayTF.getText()) >28){
                    throw new DateNotExistException();
                }
                else if (Integer.parseInt(yearTF.getText())%4 == 0 && Integer.parseInt(dayTF.getText()) >29){
                    throw new DateNotExistException();
                }
            }
            
            double current = Double.parseDouble(currentTF.getText());
            double hours = Double.parseDouble(timeTF.getText());
            int day = Integer.parseInt(dayTF.getText());
            int month = Integer.parseInt(monthTF.getText());
            int year = Integer.parseInt(yearTF.getText());
            
            boolean metalsExists = false;
            for(int i=0; i<20; i++) {
                if(metalTF.getText().equals(metalsArr[i])) {
                    metalsExists = true;
                    
                }
            }
            
            if(!metalsExists) {
                throw new MetalDoesNotExistException();
            }
            
            
            //CALCULATIONS
            ChemCalculation obj = new ChemCalculation();
            
            for(int c = 0; c < 20; c++) {
                if(metalTF.getText().equals(metalsArr[c])) {
                    metalProduced = obj.calculateMetalProduced(current, hours, molarMass[c], c, electrons[c]);//current * (hours*3600) / 96485 * molarMass[c] /electrons[c];
                    metalProducedTF.setText(String.format("%,.2fg of %s(s)", metalProduced, metalsArr[c]));
                    metalProducedPanel.setVisible(true);
                }
            }
        } catch(BlankException ex) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields.", "Notification", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "The input in the number fields should be numbers.", "Notification", JOptionPane.INFORMATION_MESSAGE);
        } catch(WrongDateException ex) {
            JOptionPane.showMessageDialog(this, "Please fill in date with the correct format (mm/dd/yy).", "Notification", JOptionPane.INFORMATION_MESSAGE);
        } catch(DateNotExistException ex) {
            JOptionPane.showMessageDialog(this, "That date does not exist.", "Notification", JOptionPane.INFORMATION_MESSAGE);
        } catch(MetalDoesNotExistException e) {
            JOptionPane.showMessageDialog(this, "The metal entered does not exist.", "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        File file = new File("metalProduction.txt");

        try{
            if(!file.exists()) {
                file.createNewFile();
            }
            FileWriter fileW = new FileWriter(file, true);
            FileReader fileR = new FileReader(file);
            BufferedReader reader = new BufferedReader(fileR);
            String line;

            //MAKING AN ENTRY
            fileW.write(userEmail + "'" + metalTF.getText() + "'" + currentTF.getText() + "'" + timeTF.getText() + "'" + metalProduced + "'" + dayTF.getText() + "/" + monthTF.getText() + "/" + yearTF.getText() + "\r");
            fileW.flush();
            JOptionPane.showMessageDialog(this, "Entry successfully saved!");

            //CLOSING
            fileW.close();
            fileR.close();
            reader.close();

            
        } catch(IOException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        metalProducedPanel.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void metalTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metalTFMouseClicked
        metalProducedPanel.setVisible(false);
        metalTF.setText("");
    }//GEN-LAST:event_metalTFMouseClicked

    private void currentTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentTFMouseClicked
        metalProducedPanel.setVisible(false);
        currentTF.setText("");
    }//GEN-LAST:event_currentTFMouseClicked

    private void timeTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTFMouseClicked
        metalProducedPanel.setVisible(false);
        timeTF.setText("");
    }//GEN-LAST:event_timeTFMouseClicked

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        new MetalProdCalcHistory().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_historyButtonActionPerformed

    private void dayTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayTFMouseClicked
        dayTF.setText("");
    }//GEN-LAST:event_dayTFMouseClicked

    private void yearTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearTFMouseClicked
        yearTF.setText("");
    }//GEN-LAST:event_yearTFMouseClicked

    private void monthTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthTFMouseClicked
        monthTF.setText("");
    }//GEN-LAST:event_monthTFMouseClicked

    private void productionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionButtonActionPerformed
        new MetalProdCalcSummary().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_productionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JPanel calculationPanel;
    private javax.swing.JButton calculatorButton;
    private javax.swing.JLabel currentLabel;
    private javax.swing.JTextField currentTF;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dayTF;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JPanel mainBackgroundPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel metalProducedPanel;
    private javax.swing.JTextField metalProducedTF;
    private javax.swing.JTextField metalTF;
    private javax.swing.JLabel metallLabel;
    private javax.swing.JTextField monthTF;
    private javax.swing.JButton productionButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField timeTF;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables

}

    class MetalDoesNotExistException extends Exception{
        public MetalDoesNotExistException() {

        }
    }


