package electrolysis;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.*;
import java.util.StringTokenizer;
import javax.swing.*;
/**
 *
 * @author ASPIRE P2QG
 */
public class UpdateAccountFrame extends javax.swing.JFrame {
    public static String uEmail = Menu1stFrame.userEmail;
    
    /**
     * Creates new form StartingFrame
     */
    public UpdateAccountFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBackgroundPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        updateAccountPanel = new javax.swing.JPanel();
        emailLabel1 = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        emailTF1 = new javax.swing.JTextField();
        passwordPF1 = new javax.swing.JPasswordField();
        namelLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        yourScienceHelperLabel = new javax.swing.JLabel();
        nameCardBackgroundPanel2 = new javax.swing.JPanel();
        nameOfAppLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sciencebook");
        setBackground(new java.awt.Color(47, 87, 85));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        mainBackgroundPanel.setBackground(new java.awt.Color(38, 38, 38));
        mainBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 10));
        mainBackgroundPanel.setPreferredSize(new java.awt.Dimension(766, 450));

        exitButton.setBackground(new java.awt.Color(0, 204, 204));
        exitButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(38, 38, 38));
        exitButton.setText("Back");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        updateAccountPanel.setBackground(new java.awt.Color(38, 38, 38));
        updateAccountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 4), " UPDATE ACCOUNT ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Demi", 0, 18), new java.awt.Color(0, 255, 255))); // NOI18N

        emailLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(0, 255, 255));
        emailLabel1.setText("Email:");

        passwordLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(0, 255, 255));
        passwordLabel1.setText("Password:");

        updateButton.setBackground(new java.awt.Color(0, 255, 255));
        updateButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 2, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(38, 38, 38));
        updateButton.setText("UPDATE ACCOUNT");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        emailTF1.setEditable(false);
        emailTF1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        emailTF1.setForeground(new java.awt.Color(38, 38, 38));
        emailTF1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        passwordPF1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        passwordPF1.setForeground(new java.awt.Color(38, 38, 38));
        passwordPF1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        namelLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        namelLabel.setForeground(new java.awt.Color(0, 255, 255));
        namelLabel.setText("Name:");

        nameTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        nameTF.setForeground(new java.awt.Color(38, 38, 38));
        nameTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));

        ageLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(0, 255, 255));
        ageLabel.setText("Age:");

        ageTF.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        ageTF.setForeground(new java.awt.Color(38, 38, 38));
        ageTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ageTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout updateAccountPanelLayout = new javax.swing.GroupLayout(updateAccountPanel);
        updateAccountPanel.setLayout(updateAccountPanelLayout);
        updateAccountPanelLayout.setHorizontalGroup(
            updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAccountPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namelLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTF1)
                    .addComponent(passwordPF1)
                    .addComponent(nameTF)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(updateAccountPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        updateAccountPanelLayout.setVerticalGroup(
            updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAccountPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelLabel)
                    .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTF, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel1)
                    .addComponent(emailTF1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGroup(updateAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAccountPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(passwordLabel1))
                    .addGroup(updateAccountPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        yourScienceHelperLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 18)); // NOI18N
        yourScienceHelperLabel.setForeground(new java.awt.Color(0, 255, 255));
        yourScienceHelperLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourScienceHelperLabel.setText("YOUR SCIENCE HELPER");

        nameCardBackgroundPanel2.setBackground(new java.awt.Color(0, 255, 255));

        nameOfAppLabel2.setBackground(new java.awt.Color(243, 243, 120));
        nameOfAppLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        nameOfAppLabel2.setForeground(new java.awt.Color(38, 38, 38));
        nameOfAppLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameOfAppLabel2.setText("SCIENCEBOOK");

        javax.swing.GroupLayout nameCardBackgroundPanel2Layout = new javax.swing.GroupLayout(nameCardBackgroundPanel2);
        nameCardBackgroundPanel2.setLayout(nameCardBackgroundPanel2Layout);
        nameCardBackgroundPanel2Layout.setHorizontalGroup(
            nameCardBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameCardBackgroundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameOfAppLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nameCardBackgroundPanel2Layout.setVerticalGroup(
            nameCardBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameOfAppLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainBackgroundPanelLayout = new javax.swing.GroupLayout(mainBackgroundPanel);
        mainBackgroundPanel.setLayout(mainBackgroundPanelLayout);
        mainBackgroundPanelLayout.setHorizontalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addGroup(mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameCardBackgroundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yourScienceHelperLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(updateAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        mainBackgroundPanelLayout.setVerticalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameCardBackgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yourScienceHelperLabel)
                .addGap(18, 18, 18)
                .addComponent(updateAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        File accounts = new File("accounts.txt");

        try{
            if(!accounts.exists()) {
                accounts.createNewFile();
            }
            FileWriter accountsFW = new FileWriter(accounts, true);
            FileReader accountsFR = new FileReader(accounts);
            BufferedReader reader = new BufferedReader(accountsFR);
            String line;

            //EXCEPTION HANDLING
            if(nameTF.getText().equals("") || ageTF.getText().equals("") || emailTF1.getText().equals("") || passwordPF1.getText().equals("")) {
                throw new BlankException();
            }
            int age = Integer.parseInt(ageTF.getText());
            if(!emailTF1.getText().contains("@")) {
                throw new WrongEmailFormatException();
            }

            //UPDATING THE ACCOUNT
            StringBuffer buffer = new StringBuffer();
            
            while ((line=reader.readLine()) != null){
                if(!line.contains(uEmail)) {
                    buffer.append(line);
                    buffer.append("\r");
		}
                else {
                    buffer.append(emailTF1.getText() + "," + nameTF.getText() + "," + ageTF.getText() + "," + passwordPF1.getText() + "\r");
                    JOptionPane.showMessageDialog(this, "Account successfully updated.", "Notification", JOptionPane.INFORMATION_MESSAGE);
                }
            }
			
            
            //CLOSING
            String fileContents = buffer.toString();
            accountsFR.close();
            reader.close();
            FileWriter fileW = new FileWriter(accounts);
            fileW.write(fileContents);
            fileW.flush();
            fileW.close();
            
            //GOING BACK
            new Menu1stFrame().setVisible(true);
            Menu1stFrame.yourScienceHelperLabel.setText("Hi, " + nameTF.getText() + "!");
            this.setVisible(false);
        } catch(IOException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch(BlankException ex) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields.", "Notification", JOptionPane.INFORMATION_MESSAGE);
        } catch(WrongEmailFormatException ex) {
            JOptionPane.showMessageDialog(this, "The entered email is invalid.", "Notification", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "The input in the age field should be an integer.", "Notification", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        new Menu1stFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    public static javax.swing.JTextField ageTF;
    private javax.swing.JLabel emailLabel1;
    public static javax.swing.JTextField emailTF1;
    private static javax.swing.JButton exitButton;
    private javax.swing.JPanel mainBackgroundPanel;
    private javax.swing.JPanel nameCardBackgroundPanel2;
    private javax.swing.JLabel nameOfAppLabel2;
    public static javax.swing.JTextField nameTF;
    private javax.swing.JLabel namelLabel;
    private javax.swing.JLabel passwordLabel1;
    public static javax.swing.JPasswordField passwordPF1;
    private javax.swing.JPanel updateAccountPanel;
    public static javax.swing.JButton updateButton;
    private javax.swing.JLabel yourScienceHelperLabel;
    // End of variables declaration//GEN-END:variables

}


